DATA_DIR = "data"
PROCESSED_DIR = "processed"
CV_FOLDS = 3
TARGET = "applause"

NON_PREDICTORS_GLOBAL = [
            TARGET,
            'index',
            'comments',
            'description',
            'duration',
            'event',
            'film_date',
            'languages',
            'main_speaker',
            'name',
            'published_date',
            'published_year',
            'ratings',
            'related_talks',
            'speaker_occupation',
            'tags',
            'title',
            'url',
            'views',
            'music',
            'conversation',
            'transcript',
            'persuasive',
            'inspiring',
            'unconvincing',
            'applause',
            'norm_persuasive',
            'norm_inspiring',
            'norm_unconvincing',
            'transcript_1sthalf',
            'transcript_2ndhalf',
            'transcript_1q',
            'transcript_2q',
            'transcript_3q',
            'transcript_4q',
            'WC',
            'Dic',
            'Analytic',
            'Clout',
            'Authentic',
            'Tone',
            'AllPunc',
            'Period',
            'Comma',
            'Colon',
            'SemiC',
            'QMark',
            'Exclam',
            'Dash',
            'Quote',
            'Apostro',
            'Parenth',
            'OtherP']


NON_PREDICTORS_LING = [
            TARGET,
            'index',
            'comments',
            'description',
            'duration',
            'event',
            'film_date',
            'languages',
            'main_speaker',
            'name',
            'published_date',
            'ratings',
            'related_talks',
            'speaker_occupation',
            'tags',
            'title',
            'url',
            'views',
            'music',
            'conversation',
            'transcript',
            'persuasive',
            'inspiring',
            'unconvincing',
            'applause',
            'laughter',
            'norm_persuasive',
            'norm_inspiring',
            'norm_unconvincing',
            'transcript_1sthalf',
            'transcript_2ndhalf',
            'transcript_1q',
            'transcript_2q',
            'transcript_3q',
            'transcript_4q',
            'WC',
            'Dic',
            'Analytic',
            'Clout',
            'Authentic',
            'Tone',
            'AllPunc',
            'Period',
            'Comma',
            'Colon',
            'SemiC',
            'QMark',
            'Exclam',
            'Dash',
            'Quote',
            'Apostro',
            'Parenth',
            'OtherP',
            'HarmVirtue',
            'HarmVice',
            'FairnessVirtue',
            'FairnessVice',
            'IngroupVirtue',
            'IngroupVice',
            'AuthorityVirtue',
            'AuthorityVice',
            'PurityVirtue',
            'PurityVice',
            'MoralityGeneral',
            'affect_1h',
            'posemo_1h',
            'negemo_1h',
            'anx_1h',
            'anger_1h',
            'sad_1h',
            'affect_2h',
            'posemo_2h',
            'negemo_2h',
            'anx_2h',
            'anger_2h',
            'sad_2h',
            'affect_1q',
            'posemo_1q',
            'negemo_1q',
            'anx_1q',
            'anger_1q',
            'sad_1q',
            'affect_2q',
            'posemo_2q',
            'negemo_2q',
            'anx_2q',
            'anger_2q',
            'sad_2q',
            'affect_3q',
            'posemo_3q',
            'negemo_3q',
            'anx_3q',
            'anger_3q',
            'sad_3q',
            'affect_4q',
            'posemo_4q',
            'negemo_4q',
            'anx_4q',
            'anger_4q',
            'sad_4q',
            'posemo_change_h',
            'negemo_change_h',
            'affect_change_h',
            'posemo_change_q',
            'negemo_change_q',
            'affect_change_q',
            'published_year',
            'Harm',
            'Fairness',
            'Purity',
            'Ingroup',
            'Authority']

NON_PREDICTORS_SENT = [
            TARGET,
            'index',
            'comments',
            'description',
            'duration',
            'event',
            'film_date',
            'languages',
            'main_speaker',
            'name',
            'published_date',
            'ratings',
            'related_talks',
            'speaker_occupation',
            'tags',
            'title',
            'url',
            'views',
            'music',
            'conversation',
            'transcript',
            'persuasive',
            'inspiring',
            'unconvincing',
            'applause',
            'laughter',
            'norm_persuasive',
            'norm_inspiring',
            'norm_unconvincing',
            'transcript_1sthalf',
            'transcript_2ndhalf',
            'transcript_1q',
            'transcript_2q',
            'transcript_3q',
            'transcript_4q',
            'WC',
            'Analytic',
            'Clout',
            'Authentic',
            'Tone',
            'WPS',
            'Sixltr',
            'Dic',
            'function',
            'pronoun',
            'ppron',
            'i',
            'we',
            'you',
            'shehe',
            'they',
            'ipron',
            'article',
            'prep',
            'auxverb',
            'adverb',
            'conj',
            'negate',
            'verb',
            'adj',
            'compare',
            'interrog',
            'number',
            'quant',
            'social',
            'family',
            'friend',
            'female',
            'male',
            'cogproc',
            'insight',
            'cause',
            'discrep',
            'tentat',
            'certain',
            'differ',
            'percept',
            'see',
            'hear',
            'feel',
            'bio',
            'body',
            'health',
            'sexual',
            'ingest',
            'drives',
            'affiliation',
            'achieve',
            'power',
            'reward',
            'risk',
            'focuspast',
            'focuspresent',
            'focusfuture',
            'relativ',
            'motion',
            'space',
            'time',
            'work',
            'leisure',
            'home',
            'money',
            'relig',
            'death',
            'informal',
            'swear',
            'netspeak',
            'assent',
            'nonflu',
            'filler',
            'AllPunc',
            'Period',
            'Comma',
            'Colon',
            'SemiC',
            'QMark',
            'Exclam',
            'Dash',
            'Quote',
            'Apostro',
            'Parenth',
            'OtherP',
            'Moral',
            'HarmVirtue',
            'HarmVice',
            'FairnessVirtue',
            'FairnessVice',
            'IngroupVirtue',
            'IngroupVice',
            'AuthorityVirtue',
            'AuthorityVice',
            'PurityVirtue',
            'PurityVice',
            'MoralityGeneral',
            'published_year',
            'Harm',
            'Fairness',
            'Purity',
            'Ingroup',
            'Authority']

NON_PREDICTORS_MORAL = [
            TARGET,
            'index',
            'comments',
            'description',
            'duration',
            'event',
            'film_date',
            'languages',
            'main_speaker',
            'name',
            'published_date',
            'ratings',
            'related_talks',
            'speaker_occupation',
            'tags',
            'title',
            'url',
            'views',
            'music',
            'conversation',
            'transcript',
            'persuasive',
            'inspiring',
            'unconvincing',
            'applause',
            'laughter',
            'norm_persuasive',
            'norm_inspiring',
            'norm_unconvincing',
            'transcript_1sthalf',
            'transcript_2ndhalf',
            'transcript_1q',
            'transcript_2q',
            'transcript_3q',
            'transcript_4q',
            'WC',
            'Analytic',
            'Clout',
            'Authentic',
            'Tone',
            'WPS',
            'Sixltr',
            'Dic',
            'function',
            'pronoun',
            'ppron',
            'i',
            'we',
            'you',
            'shehe',
            'they',
            'ipron',
            'article',
            'prep',
            'auxverb',
            'adverb',
            'conj',
            'negate',
            'verb',
            'adj',
            'compare',
            'interrog',
            'number',
            'quant',
            'affect',
            'posemo',
            'negemo',
            'anx',
            'anger',
            'sad',
            'social',
            'family',
            'friend',
            'female',
            'male',
            'cogproc',
            'insight',
            'cause',
            'discrep',
            'tentat',
            'certain',
            'differ',
            'percept',
            'see',
            'hear',
            'feel',
            'bio',
            'body',
            'health',
            'sexual',
            'ingest',
            'drives',
            'affiliation',
            'achieve',
            'power',
            'reward',
            'risk',
            'focuspast',
            'focuspresent',
            'focusfuture',
            'relativ',
            'motion',
            'space',
            'time',
            'work',
            'leisure',
            'home',
            'money',
            'relig',
            'death',
            'informal',
            'swear',
            'netspeak',
            'assent',
            'nonflu',
            'filler',
            'AllPunc',
            'Period',
            'Comma',
            'Colon',
            'SemiC',
            'QMark',
            'Exclam',
            'Dash',
            'Quote',
            'Apostro',
            'Parenth',
            'OtherP',
            'affect_1h',
            'posemo_1h',
            'negemo_1h',
            'anx_1h',
            'anger_1h',
            'sad_1h',
            'affect_2h',
            'posemo_2h',
            'negemo_2h',
            'anx_2h',
            'anger_2h',
            'sad_2h',
            'affect_1q',
            'posemo_1q',
            'negemo_1q',
            'anx_1q',
            'anger_1q',
            'sad_1q',
            'affect_2q',
            'posemo_2q',
            'negemo_2q',
            'anx_2q',
            'anger_2q',
            'sad_2q',
            'affect_3q',
            'posemo_3q',
            'negemo_3q',
            'anx_3q',
            'anger_3q',
            'sad_3q',
            'affect_4q',
            'posemo_4q',
            'negemo_4q',
            'anx_4q',
            'anger_4q',
            'sad_4q',
            'posemo_change_h',
            'negemo_change_h',
            'affect_change_h',
            'posemo_change_q',
            'negemo_change_q',
            'affect_change_q',
            'published_year']






NON_PREDICTORS = NON_PREDICTORS_GLOBAL

#
# all_features = [
#             TARGET,
#             'index',
#             'comments',
#             'description',
#             'duration',
#             'event',
#             'film_date',
#             'languages',
#             'main_speaker',
#             'name',
#             'published_date',
#             'ratings',
#             'related_talks',
#             'speaker_occupation',
#             'tags',
#             'title',
#             'url',
#             'views',
#             'music',
#             'conversation',
#             'transcript',
#             'persuasive',
#             'inspiring',
#             'unconvincing',
#             'applause',
#             'laughter',
#             'norm_persuasive',
#             'norm_inspiring',
#             'norm_unconvincing',
#             'transcript_1sthalf',
#             'transcript_2ndhalf',
#             'transcript_1q',
#             'transcript_2q',
#             'transcript_3q',
#             'transcript_4q',
#             'WC',
#             'Analytic',
#             'Clout',
#             'Authentic',
#             'Tone',
#             'WPS',
#             'Sixltr',
#             'Dic',
#             'function',
#             'pronoun',
#             'ppron',
#             'i',
#             'we',
#             'you',
#             'shehe',
#             'they',
#             'ipron',
#             'article',
#             'prep',
#             'auxverb',
#             'adverb',
#             'conj',
#             'negate',
#             'verb',
#             'adj',
#             'compare',
#             'interrog',
#             'number',
#             'quant',
#             'affect',
#             'posemo',
#             'negemo',
#             'anx',
#             'anger',
#             'sad',
#             'social',
#             'family',
#             'friend',
#             'female',
#             'male',
#             'cogproc',
#             'insight',
#             'cause',
#             'discrep',
#             'tentat',
#             'certain',
#             'differ',
#             'percept',
#             'see',
#             'hear',
#             'feel',
#             'bio',
#             'body',
#             'health',
#             'sexual',
#             'ingest',
#             'drives',
#             'affiliation',
#             'achieve',
#             'power',
#             'reward',
#             'risk',
#             'focuspast',
#             'focuspresent',
#             'focusfuture',
#             'relativ',
#             'motion',
#             'space',
#             'time',
#             'work',
#             'leisure',
#             'home',
#             'money',
#             'relig',
#             'death',
#             'informal',
#             'swear',
#             'netspeak',
#             'assent',
#             'nonflu',
#             'filler',
#             'AllPunc',
#             'Period',
#             'Comma',
#             'Colon',
#             'SemiC',
#             'QMark',
#             'Exclam',
#             'Dash',
#             'Quote',
#             'Apostro',
#             'Parenth',
#             'OtherP',
#             'Moral',
#             'HarmVirtue',
#             'HarmVice',
#             'FairnessVirtue',
#             'FairnessVice',
#             'IngroupVirtue',
#             'IngroupVice',
#             'AuthorityVirtue',
#             'AuthorityVice',
#             'PurityVirtue',
#             'PurityVice',
#             'MoralityGeneral',
#             'affect_1h',
#             'posemo_1h',
#             'negemo_1h',
#             'anx_1h',
#             'anger_1h',
#             'sad_1h',
#             'affect_2h',
#             'posemo_2h',
#             'negemo_2h',
#             'anx_2h',
#             'anger_2h',
#             'sad_2h',
#             'affect_1q',
#             'posemo_1q',
#             'negemo_1q',
#             'anx_1q',
#             'anger_1q',
#             'sad_1q',
#             'affect_2q',
#             'posemo_2q',
#             'negemo_2q',
#             'anx_2q',
#             'anger_2q',
#             'sad_2q',
#             'affect_3q',
#             'posemo_3q',
#             'negemo_3q',
#             'anx_3q',
#             'anger_3q',
#             'sad_3q',
#             'affect_4q',
#             'posemo_4q',
#             'negemo_4q',
#             'anx_4q',
#             'anger_4q',
#             'sad_4q',
#             'posemo_change_h',
#             'negemo_change_h',
#             'affect_change_h',
#             'posemo_change_q',
#             'negemo_change_q',
#             'affect_change_q',
#             'published_year',
#             'Harm',
#             'Fairness',
#             'Purity',
#             'Ingroup',
#             'Authority']