DATA_DIR = "data"
PROCESSED_DIR = "processed"
TARGET = "norm_inspiring"
NON_PREDICTORS = [
            TARGET,
            'index',
            'comments',
            'description',
            'duration',
            'event',
            'film_date',
            'languages',
            'main_speaker',
            'name',
            'published_date',
            'published_year',
            'ratings',
            'related_talks',
            'speaker_occupation',
            'tags',
            'title',
            'url',
            'views',
            'music',
            'conversation',
            'transcript',
            'persuasive',
            'inspiring',
            'unconvincing',
            'applause',
            'norm_persuasive',
            'norm_inspiring',
            'norm_unconvincing',
            'transcript_1sthalf',
            'transcript_2ndhalf',
            'transcript_1q',
            'transcript_2q',
            'transcript_3q',
            'transcript_4q',
            'WC',
            'Dic',
            'Analytic',
            'Clout',
            'Authentic',
            'Tone',
            'AllPunc',
            'Period',
            'Comma',
            'Colon',
            'SemiC',
            'QMark',
            'Exclam',
            'Dash',
            'Quote',
            'Apostro',
            'Parenth',
            'OtherP']

