DATA_DIR = "data"
PROCESSED_DIR = "processed"
CV_FOLDS = 3
TARGET = "norm_inspiring"
NON_PREDICTORS = [TARGET,
                  'index',
 'comments',
 'description',
 'duration',
 'event',
 'film_date',
 'languages',
 'main_speaker',
 'name',
 'published_date',
 'ratings',
 'related_talks',
 'speaker_occupation',
 'tags',
 'title',
 'url',
 'views',
 'music',
 'conversation',
 'transcript',
 'persuasive',
 'inspiring',
 'unconvincing',
 'applause',
 'laughter',
 'norm_persuasive',
 'norm_inspiring',
 'norm_unconvincing',
 'transcript_1sthalf',
 'transcript_2ndhalf',
 'transcript_1q',
 'transcript_2q',
 'transcript_3q',
 'transcript_4q',
 'Analytic',
 'Clout',
 'Authentic',
 'Tone',
 'WPS',
 'Sixltr',
 'function',
 'AllPunc',
 'Period',
 'Comma',
 'Colon',
 'SemiC',
 'QMark',
 'Exclam',
 'Dash',
 'Quote',
 'Apostro',
 'Parenth',
 'OtherP',
 'published_year',
 'Dic',
 'WC']

